# Generated by Django 5.2.7 on 2025-11-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='quests',
            new_name='quest',
        ),
    ]
